import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Suspense } from "react";

import { Toaster } from 'react-hot-toast';
 
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300" , "400", "500", "600","700","800","900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning={true}
        className={`${poppins.className} antialiased`}
      >
        <Suspense>
          {children}
          <Toaster
              position="top-center"
              reverseOrder={false}
              toastOptions={{
                className: ' toast',
                 style: {
                  
                    padding: '8px',
                    color: 'BLACK',
                    backgroundColor: '#FFFFFF',
                    fontSize: '.8rem'
                 },
                 success: {
                  style: {

                  },
                },
              }}

            />
        </Suspense>
      </body>
    </html>
  );
}
